version: '3.9'
services:
  mongo:
    image: mongo:7
    container_name: covid-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    container_name: covid-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
volumes:
  mongo_data:
  redis_data: