-- Performance optimization strategies for this project
USE ROLE SYSADMIN;
USE WAREHOUSE COVID_WH;
USE DATABASE COVID_APP;
USE SCHEMA PUBLIC;

-- 1) Warehouse sizing
-- Start with XSMALL and scale up temporarily for heavy jobs
-- ALTER WAREHOUSE COVID_WH SET WAREHOUSE_SIZE='SMALL';
-- ALTER WAREHOUSE COVID_WH SUSPEND; -- ensure auto-suspend is enabled

-- 2) Query Acceleration Service (optional on higher editions)
-- ALTER WAREHOUSE COVID_WH SET QUERY_ACCELERATION_MAX_SCALE_FACTOR = 8;

-- 3) Create pre-aggregated table for frequent queries
CREATE OR REPLACE TRANSIENT TABLE AGG_COUNTRY_DAILY AS
SELECT COUNTRY_REGION, DATE,
       SUM(NEW_CONFIRMED) AS NEW_CASES,
       SUM(NEW_DEATHS) AS NEW_DEATHS
FROM V_JHU_GLOBAL
GROUP BY COUNTRY_REGION, DATE;

-- 4) Consider clustering keys on large tables (for native tables)
-- ALTER TABLE AGG_COUNTRY_DAILY CLUSTER BY (COUNTRY_REGION, DATE);

-- 5) Create a task to refresh aggregates daily (requires ACCOUNTADMIN to enable)
-- CREATE OR REPLACE TASK TASK_REFRESH_AGG
--   WAREHOUSE = COVID_WH
--   SCHEDULE = 'USING CRON 0 3 * * * America/New_York'
-- AS
--   CREATE OR REPLACE TRANSIENT TABLE AGG_COUNTRY_DAILY AS
--   SELECT COUNTRY_REGION, DATE,
--          SUM(NEW_CONFIRMED) AS NEW_CASES,
--          SUM(NEW_DEATHS) AS NEW_DEATHS
--   FROM V_JHU_GLOBAL
--   GROUP BY COUNTRY_REGION, DATE;
-- ALTER TASK TASK_REFRESH_AGG RESUME;

-- 6) Privileges for app role (example)
-- CREATE ROLE COVID_APP_ROLE; GRANT USAGE ON WAREHOUSE COVID_WH TO ROLE COVID_APP_ROLE;
-- GRANT USAGE ON DATABASE COVID_APP TO ROLE COVID_APP_ROLE;
-- GRANT USAGE ON SCHEMA COVID_APP.PUBLIC TO ROLE COVID_APP_ROLE;
-- GRANT SELECT ON ALL VIEWS IN SCHEMA COVID_APP.PUBLIC TO ROLE COVID_APP_ROLE;