-- Set role
USE ROLE SYSADMIN;

-- Create warehouse and attach resource monitor
CREATE OR REPLACE WAREHOUSE COVID_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for COVID app';

USE ROLE ACCOUNTADMIN;
ALTER WAREHOUSE COVID_WH SET RESOURCE_MONITOR = RM_COVID;
USE ROLE SYSADMIN;

-- Create database and schema for our app
CREATE OR REPLACE DATABASE COVID_APP;
CREATE OR REPLACE SCHEMA COVID_APP.PUBLIC;

-- Assume Marketplace DB name from Starschema is COVID19_BY_STARSCHEMA
-- If different, change PROVIDER_DB accordingly
SET PROVIDER_DB = 'COVID19_BY_STARSCHEMA';

-- Create convenience views in our schema
CREATE OR REPLACE VIEW COVID_APP.PUBLIC.V_JHU_GLOBAL AS
SELECT * FROM IDENTIFIER($PROVIDER_DB || '.PUBLIC.JHU_GLOBAL');

CREATE OR REPLACE VIEW COVID_APP.PUBLIC.V_JHU_US AS
SELECT * FROM IDENTIFIER($PROVIDER_DB || '.PUBLIC.JHU_US');

-- Pattern recognition view for surges using MATCH_RECOGNIZE
CREATE OR REPLACE VIEW COVID_APP.PUBLIC.V_PATTERN_SURGE AS
SELECT * FROM (
  SELECT COUNTRY_REGION, PROVINCE_STATE, DATE, NEW_CONFIRMED
  FROM COVID_APP.PUBLIC.V_JHU_GLOBAL
)
MATCH_RECOGNIZE (
  PARTITION BY COUNTRY_REGION
  ORDER BY DATE
  MEASURES
    FIRST(DATE) AS start_date,
    LAST(DATE) AS end_date,
    AVG(NEW_CONFIRMED) AS avg_cases
  ONE ROW PER MATCH
  AFTER MATCH SKIP TO LAST UP
  PATTERN (STABLE* UP{3,} STABLE*)
  DEFINE
    STABLE AS NEW_CONFIRMED BETWEEN 0 AND 100,
    UP AS NEW_CONFIRMED > PREV(NEW_CONFIRMED)
);

-- Grant minimal usage to PUBLIC role for testing
GRANT USAGE ON DATABASE COVID_APP TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA COVID_APP.PUBLIC TO ROLE PUBLIC;
GRANT SELECT ON ALL VIEWS IN SCHEMA COVID_APP.PUBLIC TO ROLE PUBLIC;