-- Create a data share exposing COVID_APP views
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE SHARE COVID_APP_SHARE;
GRANT USAGE ON DATABASE COVID_APP TO SHARE COVID_APP_SHARE;
GRANT USAGE ON SCHEMA COVID_APP.PUBLIC TO SHARE COVID_APP_SHARE;
GRANT SELECT ON ALL VIEWS IN SCHEMA COVID_APP.PUBLIC TO SHARE COVID_APP_SHARE;

-- Add a consumer account (replace with Bootcamp account locator)
-- Example: org/ACCOUNT_LOCATOR or just ACCOUNT_LOCATOR depending on org
-- ALTER SHARE COVID_APP_SHARE ADD ACCOUNT = <BOOTCAMP_ACCOUNT_LOCATOR>;

-- The consumer creates a database from the share on their side:
-- CREATE DATABASE COVID_APP_FROM_SHARE FROM SHARE <provider_account>.<COVID_APP_SHARE>;